version: '3.3'

services:
  worker:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: celery
    command: ["python", "executer_tasks.py"]
    depends_on:
      - celery

  celery:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: worker
    command:  ["celery", "-A", "tasks", "worker","--loglevel=INFO"]
    depends_on:
      - redis


  redis:
    image: redis:latest
    container_name: redis
    hostname: redis
    ports:
      - "6379:6379"
