# Generated by Django 2.2 on 2023-01-23 08:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin', '0003_logentry_add_action_flag_choices'),
        ('app_users', '0002_auto_20230123_0806'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bill',
            name='author',
        ),
        migrations.DeleteModel(
            name='Person',
        ),
    ]
