# Generated by Django 2.2 on 2023-01-23 11:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app_users', '0003_auto_20230123_0823'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bill',
            options={'permissions': (('can_masscreate_tag', 'Can mass create Tag'),)},
        ),
        migrations.AddField(
            model_name='bill',
            name='author',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
