# Generated by Django 2.2 on 2023-01-23 11:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_users', '0004_auto_20230123_1128'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bill',
            name='author',
        ),
    ]
